{{- if not .Values.global.production.enabled -}}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: 'pipepline-privileged-{{ .Release.Namespace }}'
subjects:
  - kind: ServiceAccount
    name: pipeline
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: 'system:openshift:scc:privileged'
{{- end }}
