{{- if and (not .Values.global.release.enabled) (not .Values.global.production.enabled) -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-clusterbinding-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: pipeline
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-clusterrole-{{ .Release.Namespace }}
{{- end }}
