{{- if not .Values.global.production.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: docker-config
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    .dockerconfigjson: {{ .Values.docker.config.sealed }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      creationTimestamp: null
      name: docker-config
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/dockerconfigjson
{{- end }}
