{{- if .Values.global.production.enabled -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: docker-credentials
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    password: {{ .Values.docker.config.registry.password.sealed }}
    username: {{ .Values.docker.config.registry.username.sealed }}
  template:
    metadata:
      name: docker-credentials
      namespace: {{ .Release.Namespace }}
    type: Opaque
{{- end }}
