{{- if and (not .Values.global.production.enabled) .Values.git.ssh.privatekey.sealed -}}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  creationTimestamp: null
  name: git-ssh
  namespace: {{ .Release.Namespace }}
spec:
  encryptedData:
    ssh-privatekey: {{ .Values.git.ssh.privatekey.sealed }}
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
        tekton.dev/git-0: {{ .Values.git.ssh.host }}
        tekton.dev/git-1: github.com
      labels:
        {{- include "namespace.labels" . | nindent 8 }}
      name: git-ssh
      namespace: {{ .Release.Namespace }}
    type: kubernetes.io/ssh-auth
    data:
      known_hosts: |-
        [git.americancentury.collab.net]:29418,[208.75.196.162]:29418 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBBJ6REezBDvlJ2sYmZbkwS1fgbQpkkZ5Gb4vjq1ss2yj6BEf/3YagwbU/duehoDUNGs2s4tf6NSAALEJfGY7jHw=
        github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
        github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
        github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
{{- end }}
