{{- if not .Values.global.production.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pipeline
  labels:
    {{- include "namespace.labels" . | nindent 4 }}
secrets:
{{- with .Values.pipeline.serviceaccount.secrets }}
  {{- toYaml . | nindent 2 }}
{{- end }}
imagePullSecrets:
{{- with .Values.pipeline.serviceaccount.imagePullSecrets }}
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
