{{- if not .Values.global.serverless.enabled -}}
apiVersion: v1
kind: Service
metadata:
  {{- if eq .Values.global.deploymentStrategy "blue-green" }}
  name: {{ .Release.Name }}-stable
  {{- else }}
  name: {{ .Release.Name }}
  {{- end }}
  labels:
    {{- include "networking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "networking.selectorLabels" . | nindent 4 }}

{{- if eq .Values.global.deploymentStrategy "blue-green" }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-preview
  labels:
    {{- include "networking.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "networking.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
