apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-alb
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: aws-alb
    name: in-cluster
  project: devops
  source:
    helm:
      valueFiles:
        - values.yaml
    path: aws-alb
    repoURL: "https://github.com/jabf0923/matic.git"
    targetRevision: develop
  syncPolicy:
    # automated:
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
