global:
  # -- Your team name (also the prefix of your namespace name)
  teamName:
  # -- The name of the cluster in which your namespace is deployed (np-int, np-ext, pint, pext)
  cluster:
  release:
    # -- Whether this namespace is a release namespace or not, defaulted to disabled
    enabled: false

  production:
    # -- Whether this namespace is a production namespace or not, defaulted to disabled
    enabled: false
    changeRequest:
      # -- Change Request number in Service Now. This is used when checking the change
      # request status before syncing the namespace changes
      number:
      # -- The desired approval status of the change request before syncing can occur
      desiredApproval: approved
      # -- The desired state of the change request before syncing can occur
      desiredState: Ready to Implement
git:
  ssh:
    # -- The host name used for the ssh private key secret
    host: 
    privatekey:
      # -- The sealed secret for the ssh private key
      sealed:

nexusIQ:
  username:
    # -- The sealed secret for the nexus iq username for your team
    sealed:
  password:
    # -- The sealed secret for the nexus iq password for your team
    sealed:

docker:
  config:
    # -- The sealed secret for your docker registry configuration.
    # Will look like this {"auths":{"http://sonatyperepo.americancentury.com:<port>/":{"auth":"username:password"}}}
    # with a base64 encoded username and password
    sealed:
    registry:
      # -- The url of our sonatyperepo instance
      base: sonatyperepo.americancentury.com
      port:
        # -- The nonprod port for your team's docker registry
        nonprod:
        # -- The prod port for your team's docker registry
        prod:
      username:
        # -- The sealed secret for the docker registry username for your team
        sealed:
      password:
        # -- The sealed secret for the docker registry password for your team
        sealed:

ruby:
  # -- Determines if your team needs to have values/config files for python or not
  enabled: false

pipeline:
  serviceaccount:
    # -- Enable the pipeline service account
    enabled: true
    # -- The secrets used in the pipeline service account
    secrets:
      - name: git-ssh
      - name: docker-config
      - name: nexus-iq-credentials
    # -- Any image pull secrets needed for the pipeline. By default we allow annonymous pulls and don't need these
    imagePullSecrets: []

chartpublish:
  # -- Enable chartpublish helm chart support
  enabled: false
  ghToken:
    # -- The sealed secret for the github token
    sealed:



