apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://storage.googleapis.com/tekton-releases/pipeline/previous/v0.35.1/release.yaml
  - cluster-tasks/buildah.yaml
  - cluster-tasks/openshift-cli.yaml
  - cluster-tasks/prune-pipelineruns.yaml
  - cluster-tasks/helm-publish.yaml
  - cluster-tasks/deploy-task.yaml
  - cluster-tasks/finally.yaml
