apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-develop-applications
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: devops
  source:
    path: argocd
    directory:
      recurse: true
    repoURL: "git@github.com:jabf0923/matic"
    targetRevision: develop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
