apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: demo
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: "demo-develop"
      server: "https://kubernetes.default.svc"
    - namespace: "demo-release"
      server: "https://kubernetes.default.svc"
    - namespace: "demo"
      server: "https://kubernetes.default.svc"
  sourceRepos:
    - "https://github.com/jabf0923/matic.git"
