apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: demo-ssh-privatekey
  namespace: argocd
spec:
  encryptedData:
    ssh-privatekey: # add ssh key for github and seal it cluster wide with kubeseal
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: demo-ssh-privatekey
      namespace: argocd
    type: kubernetes.io/ssh-auth
